#! /bin/bash
#
# openvpn-client    Start/Stop the openvpn client
#
# chkconfig: 2345 90 60
# description: start openvpn client at boot
# processname: openvpn

# Source function library.
#. /etc/init.d/functions
. /lib/lsb/init-functions

prog="openvpn-client"
conf_file="/etc/init.d/openvpn"

start() {
    echo -n $"Starting $prog: "
        if [ -e /etc/openvpn/keys/openvpn-client ] && [ $(pgrep -fl "$conf_file start" | wc -l) -gt 0 ]; then
        log_failure_msg "[ FAILED ]"
        echo
        exit 1
    fi
    ps aux | grep openvpn/client.conf | grep -v grep > /dev/null 2>&1
    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
        pid=$(ps -ef | grep openvpn/client.conf | grep -v grep | awk '{ print $2 }')
        echo $"$prog (pid $pid) already started"
    else
        $conf_file start >/dev/null 2>&1 && log_success_msg "[ OK ]" || log_failure_msg "[ FAILED ]"
        RETVAL=$?
        return $RETVAL
    fi
}

stop() {
    echo -n $"Stopping $prog: "
    ps aux | grep openvpn/client.conf | grep -v grep > /dev/null 2>&1
    if [ $? -eq 0 ]; then
       $conf_file stop > /dev/null 2>&1 && log_success_msg "[ OK ]" || log_failure_msg "[ FAILED ]"
       RETVAL=$?
    else
       echo $"$prog already stopped"
    fi
    return $RETVAL
}

status() {
    ps aux | grep openvpn/client.conf | grep -v grep > /dev/null 2>&1
    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
        pid=$(ps -ef | grep openvpn/client.conf | grep -v grep | awk '{ print $2 }')
        echo $"$prog (pid $pid) is running..."
    else
        echo $"$prog is stopped"
    fi
}

restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    status)
        status
        ;;
    condrestart)
        [ -f /etc/openvpn/keys/openvpn-client ] && restart || :
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart}"
        exit 1
esac
